version: "3.9"

services:
  rag-app:
    image: rag-app
    container_name: rag-app
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"